spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teeth?serverTimezone=Europe/Warsaw
    username: root
    password: mysqlscout89
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 1086611284685-p4lqbqhe5ea1dti8vjlb4roagni0gcp6.apps.googleusercontent.com
#            client-secret: 5SPt_Q2fymCkW72H62PiaUoP

#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'

google:
  client:
    clientId: 1086611284685-p4lqbqhe5ea1dti8vjlb4roagni0gcp6.apps.googleusercontent.com
    clientSecret: 5SPt_Q2fymCkW72H62PiaUoP
    accessTokenUri: https://oauth2.googleapis.com/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: https://www.googleapis.com/auth/calendar profile email
    redirectUri: http://localhost:8080/calendar/authorizecal
  resource:
    userInfoUri:  https://www.googleapis.com/oauth2/v3/userinfo